/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.TaiKhoanNVDAO;
import Entities.TKHoatDong;
import Entities.TaiKhoanNV;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DangNhap extends javax.swing.JDialog {
    public DangNhap() {
//        super(parent, modal);
        initComponents();
        this.setTitle("Login");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jFrame = new javax.swing.JPanel();
        txtDNUsername = new javax.swing.JTextField();
        lblDNLogin = new javax.swing.JLabel();
        lblDNUsername = new javax.swing.JLabel();
        lblDNPassword = new javax.swing.JLabel();
        txtDNPassword = new javax.swing.JPasswordField();
        btnDNLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkGradientFocus(600);
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 0, 153));

        jFrame.setBackground(new java.awt.Color(255, 255, 255));
        jFrame.setForeground(new java.awt.Color(102, 102, 102));

        txtDNUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDNUsername.setForeground(new java.awt.Color(102, 102, 102));
        txtDNUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        lblDNLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDNLogin.setForeground(new java.awt.Color(102, 102, 102));
        lblDNLogin.setText("LOGIN");

        lblDNUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDNUsername.setForeground(new java.awt.Color(153, 153, 153));
        lblDNUsername.setText("Username");

        lblDNPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDNPassword.setForeground(new java.awt.Color(153, 153, 153));
        lblDNPassword.setText("Password");

        txtDNPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDNPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtDNPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        txtDNPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNPasswordActionPerformed(evt);
            }
        });

        btnDNLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnDNLogin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDNLogin.setForeground(new java.awt.Color(153, 0, 255));
        btnDNLogin.setText("LOGIN");
        btnDNLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameLayout = new javax.swing.GroupLayout(jFrame);
        jFrame.setLayout(jFrameLayout);
        jFrameLayout.setHorizontalGroup(
            jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDNLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addGroup(jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDNLogin)
                        .addGroup(jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDNPassword)
                            .addComponent(lblDNUsername)
                            .addComponent(txtDNUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(txtDNPassword))))
                .addGap(45, 45, 45))
        );
        jFrameLayout.setVerticalGroup(
            jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblDNLogin)
                .addGap(30, 30, 30)
                .addComponent(lblDNUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDNUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblDNPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDNPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDNLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Group 7");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FPT POLYTECHNIC");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("The happiest place on earth");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome to GROUP 7 store");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addContainerGap(40, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(124, 124, 124)))))
                .addComponent(jFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNPasswordActionPerformed
        
    }//GEN-LAST:event_txtDNPasswordActionPerformed

    private void btnDNLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNLoginActionPerformed
        String sql = "Select TaiKhoan, MatKhau, Vaitro From NhanVien";
        TaiKhoanNVDAO tknvDAO = new TaiKhoanNVDAO();
        List<TaiKhoanNV> list = tknvDAO.Select(sql);

//        list.forEach((tk) -> {
//            System.out.println(tk.TaiKhoan);
//            System.out.println(tk.MatKhau);
//        });

        int ucnt = 0, cnt = list.size();
        for (int i = 0; i < list.size(); i++) {
            TaiKhoanNV tknv = list.get(i);
            if (txtDNUsername.getText().equals(tknv.TaiKhoan)) {
                if (txtDNPassword.getText().equals(tknv.MatKhau)) {
                    JOptionPane.showMessageDialog(this, "Đăng Nhập Thành Công!");
                    this.dispose();
                    if (!tknv.VaiTro) {
                        TKHoatDong.setTaiKhoan(tknv.TaiKhoan);
                        TKHoatDong.setVaiTro("0");
                        QuanLy1 frame = new QuanLy1();
                    } else {
                        TKHoatDong.setTaiKhoan(tknv.TaiKhoan);
                        TKHoatDong.setVaiTro("1");
                        QuanLy2 frame = new QuanLy2();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Sai Mật Khẩu!");
                }
            } else {
                ucnt++;
                if (ucnt == cnt)
                    JOptionPane.showMessageDialog(this, "Tài Khoản Không Tồn Tại!");
            }
        }
    }//GEN-LAST:event_btnDNLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhap dialog = new DangNhap();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDNLogin;
    private javax.swing.JPanel jFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDNLogin;
    private javax.swing.JLabel lblDNPassword;
    private javax.swing.JLabel lblDNUsername;
    private javax.swing.JPasswordField txtDNPassword;
    private javax.swing.JTextField txtDNUsername;
    // End of variables declaration//GEN-END:variables
}