/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.KhachHangDAO;
import DAO.SanPhamDAO;
import Entities.SanPham;
import Entities.TKHoatDong;
import Helper.CheckHelper;
import Helper.DialogHelper;
import java.awt.Color;
import java.awt.Image;
import java.text.DecimalFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minhchau
 */
public class SanPhamFrame extends javax.swing.JFrame {
    List<SanPham> spList;
    public SanPhamFrame() {
        initComponents();
        init();
        
    }
    void init()
    {
         setTitle("Quản Lý Sản Phẩm");
         this.pack();
         setLocationRelativeTo(null);   
         
        btnSPMinhHoa.setOpaque(false);
        btnSPMinhHoa.setContentAreaFilled(false);
        btnSPMinhHoa.setBorderPainted(false);
        
        ShowDanhSach();
        ShowThongTin(0);
        btnSPAdd.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEdit = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        btnSPNew = new javax.swing.JButton();
        btnSPAdd = new javax.swing.JButton();
        btnSPUpdate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblSPTenSP = new javax.swing.JLabel();
        lblSPMaSP = new javax.swing.JLabel();
        lblSPMinhHoa = new javax.swing.JLabel();
        lblSPTonKho = new javax.swing.JLabel();
        lblSPGia = new javax.swing.JLabel();
        txtSPMaSP = new javax.swing.JTextField();
        txtSPTenSP = new javax.swing.JTextField();
        txtSPTonKho = new javax.swing.JTextField();
        txtSPGia = new javax.swing.JTextField();
        btnSPMinhHoa = new javax.swing.JButton();
        lblSPMaDM = new javax.swing.JLabel();
        txtSPMaDM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSPDanhSach = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtSPTimKiem = new javax.swing.JTextField();
        btnSPTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kGradientPanel3.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel3.setkGradientFocus(600);
        kGradientPanel3.setkStartColor(new java.awt.Color(153, 0, 153));

        btnSPNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loop (1).png"))); // NOI18N
        btnSPNew.setText("New");
        btnSPNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPNewActionPerformed(evt);
            }
        });

        btnSPAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnSPAdd.setText("Add");
        btnSPAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPAddActionPerformed(evt);
            }
        });

        btnSPUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save.png"))); // NOI18N
        btnSPUpdate.setText("Update");
        btnSPUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPUpdateActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblSPTenSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSPTenSP.setText("Tên Sản Phẩm");

        lblSPMaSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSPMaSP.setText("Mã Sản Phẩm");

        lblSPMinhHoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSPMinhHoa.setText("Ảnh Minh Họa");

        lblSPTonKho.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSPTonKho.setText("Tồn Kho");

        lblSPGia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSPGia.setText("Giá");

        txtSPMaSP.setEditable(false);
        txtSPMaSP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtSPMaSP.setEnabled(false);

        txtSPTenSP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        txtSPTonKho.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtSPTonKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSPTonKhoActionPerformed(evt);
            }
        });

        txtSPGia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtSPGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSPGiaActionPerformed(evt);
            }
        });

        btnSPMinhHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/default.jpg"))); // NOI18N

        lblSPMaDM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSPMaDM.setText("Mã Danh Mục");

        txtSPMaDM.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtSPMaDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSPMaDMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSPMinhHoa, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSPMinhHoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSPTenSP)
                            .addComponent(lblSPMaSP))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSPMaDM, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSPMaDM)
                            .addComponent(txtSPGia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSPGia)
                            .addComponent(txtSPTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSPTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSPTonKho)
                            .addComponent(txtSPMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSPMaSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSPMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblSPTenSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSPTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSPTonKho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSPTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSPGia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSPGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSPMaDM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSPMaDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblSPMinhHoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSPMinhHoa)
                .addContainerGap())
        );

        tblSPDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Giá", "Tồn Kho"
            }
        ));
        tblSPDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSPDanhSach);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DANH SÁCH SẢN PHẨM");

        btnSPTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Start-Menu-Search-icon.png"))); // NOI18N
        btnSPTimKiem.setText("Tìm Kiếm");
        btnSPTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                .addComponent(btnSPNew, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSPTimKiem))
                        .addGap(60, 60, 60)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSPUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSPTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSPTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSPTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSPNew, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSPUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlEditLayout = new javax.swing.GroupLayout(pnlEdit);
        pnlEdit.setLayout(pnlEditLayout);
        pnlEditLayout.setHorizontalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlEditLayout.setVerticalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSPAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPAddActionPerformed
        if (KiemTra()) {
            SanPhamDAO spDAO = new SanPhamDAO();
            
            spDAO.Insert(Integer.parseInt(txtSPMaDM.getText()), 
                    txtSPTenSP.getText(), 
                    Integer.parseInt(txtSPGia.getText()), 
                    Integer.parseInt(txtSPTonKho.getText()));
            
            DialogHelper.alert(this, "Thêm mới thành công!");
            btnSPAdd.setEnabled(false);
            ShowDanhSach();
            ShowThongTin(spList.size()-1);    
        }
    }//GEN-LAST:event_btnSPAddActionPerformed

    private void btnSPUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPUpdateActionPerformed
        if (KiemTra()) {
            SanPhamDAO spDAO = new SanPhamDAO();
                        
            spDAO.Update(Integer.parseInt(txtSPMaSP.getText()), 
                    Integer.parseInt(txtSPMaDM.getText()), 
                    txtSPTenSP.getText(), 
                    Integer.parseInt(txtSPGia.getText()), 
                    Integer.parseInt(txtSPTonKho.getText()));
            
            DialogHelper.alert(this, "Cập nhật thành công!");
            ShowDanhSach();
            ShowThongTin(0);
        }        
    }//GEN-LAST:event_btnSPUpdateActionPerformed

    private void btnSPNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPNewActionPerformed
        XoaTrang();
        btnSPUpdate.setEnabled(false);
        btnSPAdd.setEnabled(true);
    }//GEN-LAST:event_btnSPNewActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void btnSPTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPTimKiemActionPerformed
        String sql = "Select * From SanPham Where MaSanPham Like ? Or TenSanPham Like ?";
        String a = txtSPTimKiem.getText().trim();
        
        SanPhamDAO spDAO = new SanPhamDAO();
        List<SanPham> tlist = spDAO.Select(sql, "%" + a + "%", "%" + a + "%");
        if (tlist.size() > 0) {
            DialogHelper.alert(this, "Tìm thành công!");
            btnSPAdd.setEnabled(false);
            DanhSach(tlist);
            ShowThongTin(0);
        } else {
            DialogHelper.alert(this, "Không tìm thấy sản phẩm với thông tin tương ứng (mã sản phẩm, tên)!");
        }
    }//GEN-LAST:event_btnSPTimKiemActionPerformed

    private void txtSPTonKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSPTonKhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSPTonKhoActionPerformed

    private void txtSPGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSPGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSPGiaActionPerformed

    private void tblSPDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPDanhSachMouseClicked
        int i = tblSPDanhSach.getSelectedRow();
        btnSPAdd.setEnabled(false);
        ShowThongTin(i);
    }//GEN-LAST:event_tblSPDanhSachMouseClicked

    private void txtSPMaDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSPMaDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSPMaDMActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (TKHoatDong.VaiTro.equals("1")) {
            this.dispose();
            QuanLy2 ql2 = new QuanLy2();
            ql2.pack();
            ql2.setVisible(true);
        } else {
            this.dispose();
            QuanLy1 ql1 = new QuanLy1();
            ql1.pack();
            ql1.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSPAdd;
    private javax.swing.JButton btnSPMinhHoa;
    private javax.swing.JButton btnSPNew;
    private javax.swing.JButton btnSPTimKiem;
    private javax.swing.JButton btnSPUpdate;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lblSPGia;
    private javax.swing.JLabel lblSPMaDM;
    private javax.swing.JLabel lblSPMaSP;
    private javax.swing.JLabel lblSPMinhHoa;
    private javax.swing.JLabel lblSPTenSP;
    private javax.swing.JLabel lblSPTonKho;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JTable tblSPDanhSach;
    private javax.swing.JTextField txtSPGia;
    private javax.swing.JTextField txtSPMaDM;
    private javax.swing.JTextField txtSPMaSP;
    private javax.swing.JTextField txtSPTenSP;
    private javax.swing.JTextField txtSPTimKiem;
    private javax.swing.JTextField txtSPTonKho;
    // End of variables declaration//GEN-END:variables
    public void ShowDanhSach() {
        SanPhamDAO spDAO = new SanPhamDAO();
        spList = spDAO.Select();
        
        DanhSach(spList);
    }
    
    public void DanhSach(List<SanPham> list) {
        DefaultTableModel model = (DefaultTableModel) tblSPDanhSach.getModel();
        model.setRowCount(0);
        
        for (SanPham sp: list) {
            Vector vector = new Vector();
            vector.add(sp.MaSP);
            vector.add(sp.Ten);
            DecimalFormat format = new DecimalFormat("###,###");
            String s = format.format(sp.Gia);
            vector.add(s + "VNĐ");
            vector.add(sp.TonKho);
            model.addRow(vector);
        }
    }
    
    public void ShowThongTin(int i) {
        btnSPUpdate.setEnabled(true);
        tblSPDanhSach.setRowSelectionInterval(i, i);
        for (SanPham sp: spList) {
            if (tblSPDanhSach.getValueAt(i, 0).toString().equals(Integer.toString(sp.MaSP))) {
                txtSPMaSP.setText(Integer.toString(sp.MaSP));
                txtSPTenSP.setText(sp.Ten);
                txtSPTonKho.setText(Integer.toString(sp.TonKho));
                txtSPGia.setText(Integer.toString(sp.Gia));
                txtSPMaDM.setText(Integer.toString(sp.MaDM));
                ImageIcon image = new ImageIcon(getClass().getResource(sp.HinhAnh));
                Image img = image.getImage().getScaledInstance(140, 140, Image.SCALE_DEFAULT);
                ImageIcon rsImage = new ImageIcon(img);
                btnSPMinhHoa.setIcon(rsImage);
            }
        }
    }
    
    public void XoaTrang() {
        int i = tblSPDanhSach.getSelectedRow();
        tblSPDanhSach.removeRowSelectionInterval(i, i);
        txtSPMaSP.setText("");
        txtSPTenSP.setText("");
        txtSPTonKho.setText("");
        txtSPGia.setText("");
        txtSPMaDM.setText("");
        ImageIcon image = new ImageIcon(getClass().getResource("/icon/default.jpg"));
        Image img = image.getImage().getScaledInstance(140, 140, Image.SCALE_DEFAULT);
        ImageIcon rsImage = new ImageIcon(img);
        btnSPMinhHoa.setIcon(rsImage);
    }
    
    public void XoaMauNen() {
        txtSPTenSP.setBackground(Color.white);
        txtSPTonKho.setBackground(Color.white);
        txtSPGia.setBackground(Color.white);
        txtSPMaDM.setBackground(Color.white);
    }
    
    public boolean KiemTra() {
        if (CheckHelper.Chuoi(txtSPTenSP.getText(), 50, "Tên sản phẩm", this)) {
            XoaMauNen();
            if (CheckHelper.SoLonHonHoacBang(txtSPTonKho.getText(), "Tồn Kho", 0, this)) {
                XoaMauNen();
                if (CheckHelper.SoLonHon(txtSPGia.getText(), "Giá", 0, this)) {
                    XoaMauNen();
                    if (CheckHelper.KhoangSo(txtSPMaDM.getText(), "Mã danh mục", 1, 3, this)) {
                        XoaMauNen();
                        return true;
                    } else {
                        txtSPMaDM.setBackground(Color.yellow);
                        return false;
                    }
                } else {
                    txtSPGia.setBackground(Color.yellow);
                    return false;
                }
            } else {
                txtSPTonKho.setBackground(Color.yellow);
                return false;
            }
        } else {
            txtSPTenSP.setBackground(Color.yellow);
            return false;
        }
    }
}
