/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.List;
import Entities.KhachHang;
import DAO.KhachHangDAO;
import Entities.TKHoatDong;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minhchau
 */
public class ThongKeKhachHang extends javax.swing.JFrame {
    List<KhachHang> khList;
    public ThongKeKhachHang() {
        initComponents();
        init();
    }
     void init()
    {
         setTitle("Thống Kê Khách Hàng");
         setLocationRelativeTo(null); 
         
         rdoTVThanhVien.setSelected(true);
         ThanhVien();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tblTVDanhSach = new javax.swing.JTable();
        rdoTVTatCa = new javax.swing.JRadioButton();
        rdoTVKhachHang = new javax.swing.JRadioButton();
        rdoTVThanhVien = new javax.swing.JRadioButton();

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kGradientPanel3.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel3.setkGradientFocus(600);
        kGradientPanel3.setkStartColor(new java.awt.Color(153, 0, 153));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("DANH SÁCH THÀNH VIÊN");

        tblTVDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên", "Email", "Số ĐT", "Địa Chỉ"
            }
        ));
        jScrollPane14.setViewportView(tblTVDanhSach);

        buttonGroup1.add(rdoTVTatCa);
        rdoTVTatCa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdoTVTatCa.setForeground(new java.awt.Color(255, 255, 255));
        rdoTVTatCa.setText("Tất Cả");
        rdoTVTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTVTatCaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoTVKhachHang);
        rdoTVKhachHang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdoTVKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        rdoTVKhachHang.setText("Chưa Là Thành Viên");
        rdoTVKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTVKhachHangActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoTVThanhVien);
        rdoTVThanhVien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdoTVThanhVien.setForeground(new java.awt.Color(255, 255, 255));
        rdoTVThanhVien.setText("Thành Viên");
        rdoTVThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTVThanhVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rdoTVThanhVien)
                        .addGap(18, 18, 18)
                        .addComponent(rdoTVKhachHang)
                        .addGap(10, 10, 10)
                        .addComponent(rdoTVTatCa))
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoTVTatCa)
                    .addComponent(rdoTVKhachHang)
                    .addComponent(rdoTVThanhVien))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void rdoTVTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTVTatCaActionPerformed
        if (rdoTVTatCa.isSelected()) {
            TatCa();
        }
    }//GEN-LAST:event_rdoTVTatCaActionPerformed

    private void rdoTVKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTVKhachHangActionPerformed
        if (rdoTVKhachHang.isSelected()) {
            KhachHang();
        }
    }//GEN-LAST:event_rdoTVKhachHangActionPerformed

    private void rdoTVThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTVThanhVienActionPerformed
        if (rdoTVThanhVien.isSelected()) {
            ThanhVien();
        }
    }//GEN-LAST:event_rdoTVThanhVienActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (TKHoatDong.VaiTro.equals("1")) {
            this.dispose();
            QuanLy2 ql2 = new QuanLy2();
            ql2.pack();
            ql2.setVisible(true);
        } else {
            this.dispose();
            QuanLy1 ql1 = new QuanLy1();
            ql1.pack();
            ql1.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JTextField jTextField1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JRadioButton rdoTVKhachHang;
    private javax.swing.JRadioButton rdoTVTatCa;
    private javax.swing.JRadioButton rdoTVThanhVien;
    private javax.swing.JTable tblTVDanhSach;
    // End of variables declaration//GEN-END:variables
    public void ThanhVien() {        
        KhachHangDAO khDAO = new KhachHangDAO();
        khList = khDAO.Select("Select * From KhachHang Where ThanhVien = 1");
        
        DanhSach(khList);
    }
    
    public void KhachHang() {
        KhachHangDAO khDAO = new KhachHangDAO();
        khList = khDAO.Select("Select * From KhachHang Where ThanhVien = 0");
        
        DanhSach(khList);
    }
    
    public void TatCa() {
        KhachHangDAO khDAO = new KhachHangDAO();
        khList = khDAO.Select();
        
        DanhSach(khList);
    }
    
    public void DanhSach(List<KhachHang> list) {
        DefaultTableModel model = (DefaultTableModel) tblTVDanhSach.getModel();
        model.setRowCount(0);
        
        for (KhachHang kh: list) {
            Vector vector = new Vector();
            vector.add(kh.MaKH);
            vector.add(kh.TenKH);
            vector.add(kh.Mail);
            vector.add(kh.SoDT);
            vector.add(kh.DiaChi);
            model.addRow(vector);
        }
    }
}
